name: spot
description: Lookup details for any website.

publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  responsive_builder: ^0.4.2
  rive: ^0.8.4
  shimmer: ^2.0.0
  stacked: ^2.2.8
  stacked_hooks: ^0.2.1+1
  stacked_services:
    git:
      url: https://github.com/thecokerdavid/stacked.git
      path: packages/stacked_services/
      ref: 6c6c7da
  stacked_themes: ^0.3.8+1
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4
  stacked_generator: ^0.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/logo/
