name: spot
description: Lookup details for any website.

publish_to: "none"

version: 1.0.3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.2.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  shimmer: ^2.0.0
  stacked: ^2.2.8
  stacked_services: ^0.8.16
  stacked_themes: ^0.3.8+1
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4
  stacked_generator: ^0.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/splash/
