name: Build and Deploy

on:
 push:
   branches:
     - master

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - run: echo "${DOTENV// /}" | base64 -d > lib/core/utils/secrets.dart
       env:
         DOTENV: ${{ secrets.DOTENV }}

     - name: Set up Flutter
       uses: subosito/flutter-action@v1
       with:
         channel: 'stable'
         flutter-version: '2.8.1'

     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2.3.1
       with:
         key: ${{ secrets.SSH_KEY }}
         name: id_rsa
         known_hosts: ${{ secrets.KNOWN_HOSTS }}

     - name: Get dependencies
       run: flutter pub get

     - name: Generate source files
       run: flutter packages pub run build_runner build --delete-conflicting-outputs

     - name: Build release
       run: flutter build web --web-renderer canvaskit

     - name: Upload artifacts
       uses: actions/upload-artifact@v1
       with:
         name: build
         path: build

 deploy-build:
   needs: build

   runs-on: ubuntu-latest

   steps:
     - name: Clone the repoitory
       uses: actions/checkout@v2
       with:
         ref: build

     - name: Configure git
       run: |
         git config --global user.email ${GITHUB_ACTOR}@gmail.com
         git config --global user.name ${GITHUB_ACTOR}

     - name: Download website build
       uses: actions/download-artifact@v1
       with:
         name: build
         path: build

     - name: Commit and Push
       run: |
         if [ $(git status --porcelain=v1 2>/dev/null | wc -l) != "0" ] ; then
           git add -f build
           git commit -m "gh-actions deployed a new build"
           git push --force https://github.com/${GITHUB_REPOSITORY}.git HEAD:build
         fi
