name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
            flutter-version: '2.8.1'
      - run: echo $SECRETS_FILE_CONTENT | base64 -d > lib/utils/secrets.dart
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build web
